name: Dan LAtham
favicon: null
layout_spectrum: 0.7726568302605301
typography_spectrum: 0.5733196653891355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.46404925966635346
  lightness: 0.4720391589216888
  saturation: 0.5452579406555742
  rhythmicContrast: 0.6231584828346968
purpose: []
