name: Dan LAtham
favicon: null
layout_spectrum: 0.25653
typography_spectrum: 0.08887
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7deff'
    - '#6d92b4'
    - '#78716a'
    - '#0e100f'
    - '#434930'
  brandStrength: 0.46404925966635346
  lightness: 0.4720391589216888
  saturation: 0.5
  rhythmicContrast: 0.6231584828346968
purpose: []
